### ISSUE TITLE
Write a guide to nick registration on Rizon

### ISSUE THREAD

**Issue by ajimu** [softpunk/softpunk.github.io#1]
We currently link to the [Rizon wiki](https://wiki.rizon.net/index.php?title=Nick_Registration), but it's a bit more tedious than I'd like. We can (and maybe _should_) link to the wiki for further info

**Comment by nv-vn** [comment]
I think it'd probably be a good idea to add a guide to use SSL with some commob clients (even if just the link to the Rizon wiki for that) as well, in that case.
